---
- name: Check if node_exporter exists
  stat:
    path: /usr/local/bin/node_exporter
  register: register_node_exporter
- name: Download node_exporter from source
  unarchive:
    src: "{{ node_exporter.src }}"
    dest: /tmp
    remote_src: yes
  when: register_node_exporter.stat.exists == False
- name: Move node_exporter
  # FIXME: version変更の時に旧バージョンが自動で削除されないので、symlinkとかで対応したい
  command: "mv /tmp/node_exporter-{{ node_exporter.version }}/node_exporter /usr/local/bin/node_exporter"
  when: register_node_exporter.stat.exists == False
- name: Create node_exporter user
  user:
    name: node_exporter
    state: present
    system: yes
- name: Create node_exporter.service
  template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
- name: Create node_exporter.socket
  template:
    src: node_exporter.socket
    dest: /etc/systemd/system/node_exporter.socket
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Start node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
