---
- name: Add Docker repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=armhf] https://download.docker.com/linux/raspbian bullseye stable"
    create: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CE, Docker CE CLI, and Containerd.io
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Enable the user to run Docker commands
  ansible.builtin.user:
    name: kazu # FIXME: Pass it as a parameter
    groups: docker
    append: yes
