---
- name: Check if Docker is installed
  command: which docker
  register: docker_installed
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Install Docker using the official Docker install script
  ansible.builtin.shell: |
    curl -sSL https://get.docker.com | sh
  become: yes
  when: docker_installed.rc != 0

- name: Check Docker installation
  ansible.builtin.command: docker --version
  register: docker_version
  failed_when: docker_version.rc != 0

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  when: docker_installed.rc != 0

- name: Enable the user to run Docker commands
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_installed.rc != 0
