- name: Configure raspi
  hosts: rasberrypi
  vars:
    node_exporter:
      version: 1.7.0.linux-armv7
      src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-armv7.tar.gz
    prometheus:
      version: 2.48.0.linux-armv7
      src: https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-armv7.tar.gz
  become: true
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: install apt packages
      apt:
        name:
          - vim
          - git
          - ufw
          - consul # TODO: move to roles
          - jq
          - ca-certificates
          - curl
          - gnupg
          - wget
          - tar
  roles:
   - docker
   - node_exporter
   - prometheus
