- name: Configure raspi
  hosts: rasberrypi
  become: true
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: install apt packages
      apt:
        name:
          - vim
          - git
          - ufw
          - consul # TODO: move to roles
          - jq
          - ca-certificates
          - curl
          - gnupg
          - wget
          - tar
  roles:
   - docker
   - node_exporter
   - prometheus
