- name: Configure raspi
  hosts: rasberrypi
  become: true
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: install apt packages
      apt:
        name:
          - vim
          - git
          - ufw
          - consul
          - jq
          - ca-certificates
          - curl
          - gnupg
          - wget
          - tar

    - name: Add Docker repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=armhf] https://download.docker.com/linux/raspbian bullseye stable"
        create: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker CE, Docker CE CLI, and Containerd.io
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
